/** @format */

import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: "I'dEffect Academy",
    description: 'Generated by create next app',
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang='en'>
            <body
                style={{
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    justifyContent: 'center',
                    minHeight: '100vh',
                    textAlign: 'center',
                    backgroundColor: '#000000',
                    backgroundImage: 'radial-gradient(#0d0d0d 25%,#1a1a1a 50%,#333 100%',
                }}
            >
                <div>{children}</div>
            </body>
        </html>
    );
};

export default RootLayout;
